import type { EventItem, FriendRequest, Message, User } from "./types";

const DAY = 24 * 60 * 60 * 1000;
const HOUR = 60 * 60 * 1000;

/** Deterministic demo users used to populate Discover Friends & event hosts. */
export const seedUsers: User[] = [
  {
    id: "u_ana",
    name: "Ana Rojas",
    handle: "anabuilds",
    bio: "Solana dev advocate. I ship on weekends and host too many meetups.",
    location: "Lisbon, PT",
    twitter: "anabuilds",
    authMethod: "wallet",
    walletAddress: "AnaRojas1111111111111111111111111111111111",
    reputation: 940,
    interests: ["DeFi", "Hackathons", "Rust"],
    createdAt: Date.now() - 40 * DAY,
    seeded: true,
  },
  {
    id: "u_kenji",
    name: "Kenji Tanaka",
    handle: "kenji",
    bio: "cNFT tinkerer. Metaplex core contributor. Coffee-driven.",
    location: "Tokyo, JP",
    authMethod: "google",
    reputation: 820,
    interests: ["NFTs", "Art", "Mobile"],
    createdAt: Date.now() - 55 * DAY,
    seeded: true,
  },
  {
    id: "u_maya",
    name: "Maya Fernandes",
    handle: "mayaf",
    bio: "Community lead @ Superteam. I turn strangers into collaborators.",
    location: "Bengaluru, IN",
    authMethod: "email",
    reputation: 1180,
    interests: ["Community", "Conferences", "DAOs"],
    createdAt: Date.now() - 70 * DAY,
    seeded: true,
  },
  {
    id: "u_leo",
    name: "Leo Martins",
    handle: "leom",
    bio: "Product designer. Pixel-perfect or nothing. Ex-Phantom.",
    location: "Berlin, DE",
    authMethod: "apple",
    reputation: 610,
    interests: ["Design", "Workshops", "Creators"],
    createdAt: Date.now() - 30 * DAY,
    seeded: true,
  },
  {
    id: "u_sara",
    name: "Sara Okonkwo",
    handle: "saraok",
    bio: "Founder building consumer crypto. Always down for a demo day.",
    location: "Lagos, NG",
    authMethod: "wallet",
    walletAddress: "SaraOkon2222222222222222222222222222222222",
    reputation: 760,
    interests: ["Startups", "Payments", "Mobile"],
    createdAt: Date.now() - 22 * DAY,
    seeded: true,
  },
  {
    id: "u_diego",
    name: "Diego Alvarez",
    handle: "diego",
    bio: "Validator operator. I like fast blocks and slow espresso.",
    location: "Mexico City, MX",
    authMethod: "wallet",
    walletAddress: "DiegoAlv3333333333333333333333333333333333",
    reputation: 500,
    interests: ["Infra", "Validators", "Rust"],
    createdAt: Date.now() - 18 * DAY,
    seeded: true,
  },
  {
    id: "u_priya",
    name: "Priya Nair",
    handle: "priya",
    bio: "Hackathon serial winner. Ask me about compressed NFTs.",
    location: "Remote",
    authMethod: "google",
    reputation: 1020,
    interests: ["Hackathons", "AI", "NFTs"],
    createdAt: Date.now() - 12 * DAY,
    seeded: true,
  },
  {
    id: "u_tom",
    name: "Tom Wilder",
    handle: "tomw",
    bio: "Writing about Solana every week. Occasional event host.",
    location: "New York, US",
    authMethod: "email",
    reputation: 430,
    interests: ["Content", "Meetups", "DeFi"],
    createdAt: Date.now() - 8 * DAY,
    seeded: true,
  },
];

const gradients = [
  "from-brand-purple to-brand-blue",
  "from-brand-blue to-brand-cyan",
  "from-brand-cyan to-brand-green",
  "from-brand-violet to-brand-purple",
  "from-fuchsia-500 to-brand-purple",
  "from-indigo-500 to-brand-blue",
  "from-brand-green to-brand-cyan",
];

export function buildSeedEvents(): EventItem[] {
  const now = Date.now();
  const base: Omit<EventItem, "coverGradient" | "createdAt">[] = [
    {
      id: "e_summit",
      title: "Solana Superteam Summit",
      description:
        "A full day of talks, workshops and demos from the best builders in the Solana ecosystem. Network with founders, devs and investors - and grab your proof-of-attendance NFT on the way out.",
      hostId: "u_maya",
      category: "Conference",
      startsAt: new Date(now + 6 * DAY + 10 * HOUR).toISOString(),
      endsAt: new Date(now + 6 * DAY + 18 * HOUR).toISOString(),
      location: "Bengaluru, IN",
      isOnline: false,
      capacity: 300,
      price: "Free",
      visibility: "public",
      requiresApproval: false,
      tokenGated: false,
      attendeeIds: ["u_maya", "u_ana", "u_priya", "u_tom"],
      tags: ["Conference", "Networking"],
    },
    {
      id: "e_cnft",
      title: "cNFT Night: Mint & Mingle",
      description:
        "An intimate evening for NFT builders and collectors. Live compressed-NFT minting, lightning talks and good vibes.",
      hostId: "u_kenji",
      category: "Meetup",
      startsAt: new Date(now + 10 * DAY + 12 * HOUR).toISOString(),
      location: "Tokyo, JP",
      isOnline: false,
      capacity: 120,
      price: "0.5 SOL",
      visibility: "public",
      requiresApproval: true,
      tokenGated: true,
      attendeeIds: ["u_kenji", "u_leo"],
      tags: ["NFT", "Meetup", "Token-gated"],
    },
    {
      id: "e_hack",
      title: "Helius Devs & Draughts Hackathon",
      description:
        "48 hours, one goal: ship something people want. Bounties, mentors and infinite cold brew. Remote-friendly with an online check-in.",
      hostId: "u_priya",
      category: "Hackathon",
      startsAt: new Date(now + 14 * DAY + 9 * HOUR).toISOString(),
      endsAt: new Date(now + 16 * DAY + 18 * HOUR).toISOString(),
      location: "Online",
      isOnline: true,
      capacity: 500,
      price: "Free",
      visibility: "public",
      requiresApproval: false,
      tokenGated: false,
      attendeeIds: ["u_priya", "u_ana", "u_diego", "u_sara"],
      tags: ["Hackathon", "Online"],
    },
    {
      id: "e_design",
      title: "Designing Wallet-Native Products",
      description:
        "A hands-on workshop on UX patterns for wallet-first apps. Bring a laptop and a Figma account.",
      hostId: "u_leo",
      category: "Workshop",
      startsAt: new Date(now + 4 * DAY + 15 * HOUR).toISOString(),
      location: "Berlin, DE",
      isOnline: false,
      capacity: 40,
      price: "Free",
      visibility: "public",
      requiresApproval: true,
      tokenGated: false,
      attendeeIds: ["u_leo", "u_tom"],
      tags: ["Design", "Workshop"],
    },
    {
      id: "e_founders",
      title: "Founders & Funders Mixer",
      description:
        "Casual drinks connecting early-stage founders with angels and funds active in crypto. Curated guest list.",
      hostId: "u_sara",
      category: "Party",
      startsAt: new Date(now + 20 * DAY + 19 * HOUR).toISOString(),
      location: "Lagos, NG",
      isOnline: false,
      capacity: 80,
      price: "Free",
      visibility: "private",
      requiresApproval: true,
      tokenGated: false,
      attendeeIds: ["u_sara", "u_maya"],
      tags: ["Startups", "Networking"],
    },
    {
      id: "e_ama",
      title: "AMA: Scaling Validators on Solana",
      description:
        "Live AMA with validator operators on hardware, MEV and staying online during congestion.",
      hostId: "u_diego",
      category: "AMA",
      startsAt: new Date(now + 2 * DAY + 17 * HOUR).toISOString(),
      location: "Online",
      isOnline: true,
      capacity: 1000,
      price: "Free",
      visibility: "public",
      requiresApproval: false,
      tokenGated: false,
      attendeeIds: ["u_diego", "u_ana"],
      tags: ["Infra", "AMA", "Online"],
    },
  ];

  return base.map((e, i) => ({
    ...e,
    coverGradient: gradients[i % gradients.length],
    createdAt: now - (i + 1) * DAY,
  }));
}

export function buildSeedMessages(): Message[] {
  const now = Date.now();
  return [
    {
      id: "m1",
      scope: "event",
      channelId: "e_summit",
      senderId: "u_maya",
      text: "Welcome everyone! 🎉 Doors open at 10am sharp. Bring your wallet for check-in.",
      createdAt: now - 5 * HOUR,
    },
    {
      id: "m2",
      scope: "event",
      channelId: "e_summit",
      senderId: "u_ana",
      text: "So hyped for this! Is there a workshop track or just talks?",
      createdAt: now - 4 * HOUR,
    },
    {
      id: "m3",
      scope: "event",
      channelId: "e_summit",
      senderId: "u_maya",
      text: "Both! Workshops in the afternoon. Full schedule drops tomorrow.",
      createdAt: now - 3.5 * HOUR,
    },
    {
      id: "m4",
      scope: "event",
      channelId: "e_summit",
      senderId: "u_tom",
      text: "Will there be POAP badges for attendance? 👀",
      createdAt: now - 90 * 60 * 1000,
    },
    {
      id: "m5",
      scope: "event",
      channelId: "e_hack",
      senderId: "u_priya",
      text: "Team formation thread - drop your skills and what you want to build!",
      createdAt: now - 2 * HOUR,
    },
    {
      id: "m6",
      scope: "event",
      channelId: "e_hack",
      senderId: "u_diego",
      text: "Infra person here, happy to help teams with RPC + validators.",
      createdAt: now - 100 * 60 * 1000,
    },
  ];
}

/** A couple of pre-existing friendships between demo users. */
export function buildSeedFriendships(): FriendRequest[] {
  const now = Date.now();
  return [
    { id: "f1", from: "u_ana", to: "u_maya", status: "accepted", createdAt: now - 20 * DAY },
    { id: "f2", from: "u_priya", to: "u_ana", status: "accepted", createdAt: now - 10 * DAY },
    { id: "f3", from: "u_kenji", to: "u_leo", status: "accepted", createdAt: now - 8 * DAY },
  ];
}
