import type { User } from "./types";

const DAY = 24 * 60 * 60 * 1000;

/**
 * Deterministic demo users, used only by the local-store fallback that runs
 * when Supabase is not configured. Everything a configured deployment shows -
 * events, messages, friendships - comes from the database.
 */
export const seedUsers: User[] = [
  {
    id: "u_ana",
    name: "Ana Rojas",
    handle: "anabuilds",
    bio: "Solana dev advocate. I ship on weekends and host too many meetups.",
    location: "Lisbon, PT",
    twitter: "anabuilds",
    authMethod: "wallet",
    walletAddress: "AnaRojas1111111111111111111111111111111111",
    reputation: 940,
    interests: ["DeFi", "Hackathons", "Rust"],
    createdAt: Date.now() - 40 * DAY,
    seeded: true,
  },
  {
    id: "u_kenji",
    name: "Kenji Tanaka",
    handle: "kenji",
    bio: "cNFT tinkerer. Metaplex core contributor. Coffee-driven.",
    location: "Tokyo, JP",
    authMethod: "google",
    reputation: 820,
    interests: ["NFTs", "Art", "Mobile"],
    createdAt: Date.now() - 55 * DAY,
    seeded: true,
  },
  {
    id: "u_maya",
    name: "Maya Fernandes",
    handle: "mayaf",
    bio: "Community lead @ Superteam. I turn strangers into collaborators.",
    location: "Bengaluru, IN",
    authMethod: "email",
    reputation: 1180,
    interests: ["Community", "Conferences", "DAOs"],
    createdAt: Date.now() - 70 * DAY,
    seeded: true,
  },
  {
    id: "u_leo",
    name: "Leo Martins",
    handle: "leom",
    bio: "Product designer. Pixel-perfect or nothing. Ex-Phantom.",
    location: "Berlin, DE",
    authMethod: "apple",
    reputation: 610,
    interests: ["Design", "Workshops", "Creators"],
    createdAt: Date.now() - 30 * DAY,
    seeded: true,
  },
  {
    id: "u_sara",
    name: "Sara Okonkwo",
    handle: "saraok",
    bio: "Founder building consumer crypto. Always down for a demo day.",
    location: "Lagos, NG",
    authMethod: "wallet",
    walletAddress: "SaraOkon2222222222222222222222222222222222",
    reputation: 760,
    interests: ["Startups", "Payments", "Mobile"],
    createdAt: Date.now() - 22 * DAY,
    seeded: true,
  },
  {
    id: "u_diego",
    name: "Diego Alvarez",
    handle: "diego",
    bio: "Validator operator. I like fast blocks and slow espresso.",
    location: "Mexico City, MX",
    authMethod: "wallet",
    walletAddress: "DiegoAlv3333333333333333333333333333333333",
    reputation: 500,
    interests: ["Infra", "Validators", "Rust"],
    createdAt: Date.now() - 18 * DAY,
    seeded: true,
  },
  {
    id: "u_priya",
    name: "Priya Nair",
    handle: "priya",
    bio: "Hackathon serial winner. Ask me about compressed NFTs.",
    location: "Remote",
    authMethod: "google",
    reputation: 1020,
    interests: ["Hackathons", "AI", "NFTs"],
    createdAt: Date.now() - 12 * DAY,
    seeded: true,
  },
  {
    id: "u_tom",
    name: "Tom Wilder",
    handle: "tomw",
    bio: "Writing about Solana every week. Occasional event host.",
    location: "New York, US",
    authMethod: "email",
    reputation: 430,
    interests: ["Content", "Meetups", "DeFi"],
    createdAt: Date.now() - 8 * DAY,
    seeded: true,
  },
];
